window.events = {
    'ev1': {
        icon: '<i class="fas fa-spell-check"></i>',
        tag: 'CYBER ETYMOLOGY',
        name: 'CYBER ETYMOLOGY',
        sub: 'Etymology: Derivation of Words from Originals',
        color: '#00f5ff',
        rules: [
            'It is a game of scrabble related to computer science.',
            '3 members per team.',
            'The game comprises of two rounds: Prelims & Finals.',
            'Each team will be given 5 characters, one at a time.',
            'Words framed with given characters should be technical terms related to electronics and computers.',
        ],
        info: [
            { icon: 'fa-users', label: 'Team Size', val: '3 members' },
            { icon: 'fa-layer-group', label: 'Rounds', val: '2 (Prelims & Finals)' },
            { icon: 'fa-map-pin', label: 'Venue', val: 'Research Lab, ISE' },
        ],
        student: 'chirashree - +91 87621 93686\nNehil - +91 91312 03322',
        faculty: 'Dr. Nagaratna B Chittaragi\n96062 25604',
    },
    'ev2': {
        icon: '<i class="fas fa-brain"></i>',
        tag: 'TECHNICAL QUIZ',
        name: 'TECHNICAL QUIZ',
        sub: 'Facts, Personalities, Logos & Industry Trends',
        color: '#b400ff',
        rules: [
            '2 members per team.',
            'The QUIZ comprises of two rounds: Prelims & Finals.',
            'Quiz will be based on facts of computer technology, famous personalities, industry logos and recent trends in IT.',
        ],
        info: [
            { icon: 'fa-users', label: 'Team Size', val: '2 members' },
            { icon: 'fa-layer-group', label: 'Rounds', val: '2 (Prelims & Finals)' },
            { icon: 'fa-map-pin', label: 'Venue', val: 'Koutilya Lab, ISE' },
        ],
        student: 'Manoj - 9008126740\nBalaji - 7090914581\nNaveen - 8618742198',
        faculty: 'Dr. Sharathkumar\n95353 21023',
    },
    'ev3': {
        icon: '<i class="fas fa-microphone"></i>',
        tag: 'WITTY BYTE',
        name: 'WITTYBYTE',
        sub: 'TECH TALK',
        color: '#39ff14',
        rules: [
            'It is an individual technical talk event.',
            'The WITTYBYTE comprises of four rounds.',
            'Tech talk will be based on talk related to a topic scenario or an image given on the spot.',
            'Usage of offensive words and violation of rules will result in immediate elimination.',
        ],
        info: [
            { icon: 'fa-user', label: 'Type', val: 'Individual' },
            { icon: 'fa-layer-group', label: 'Rounds', val: '4 rounds' },
            { icon: 'fa-map-pin', label: 'Venue', val: 'Project Lab, CSE' },
        ],
        student: 'Haradeep Reddy - 7416719446\nSachin - 9606426567',
        faculty: 'Dr. H D Kallinatha\n99862 95070',
    },
    'ev4': {
        icon: '<i class="fas fa-gamepad"></i>',
        tag: 'GAMING',
        name: 'LIFE EXTENSION',
        sub: 'GAMING CONTEST',
        color: '#ff0090',
        rules: [
            '<strong>Valorant</strong>',
            '5 members per team.',
            'Players must bring their own laptops.',
            'Internet facility will be provided.',
            '<br><strong>BGMI</strong>',
            '4 members per team.',
            'Game will be played in custom rules created by the host.',
            'Internet facility will be provided.',
        ],
        info: [
            { icon: 'fa-users', label: 'Valorant', val: '5 members' },
            { icon: 'fa-users', label: 'BGMI', val: '4 members' },
            { icon: 'fa-map-pin', label: 'Venue', val: 'Media Center/MBA Block' },
        ],
        student: 'Omsai Reddy - 8861611227\nYashaswini P - 91 80886 88451',
        faculty: 'Dr. Keerthan Kumar\n88846 74522',
    },
    'ev5': {
        icon: '<i class="fas fa-terminal"></i>',
        tag: 'PROGRAMMING',
        name: 'BYTE SURGE',
        sub: 'Programming Contest',
        color: '#ff6b1a',
        rules: [
            'It is a Programming contest.',
            '2 members per team.',
            'The BYTE SURGE comprises of two rounds: Prelims & Finals.',
            'Language: C or C++',
        ],
        info: [
            { icon: 'fa-users', label: 'Team Size', val: '2 members' },
            { icon: 'fa-code', label: 'Language', val: 'C / C++' },
            { icon: 'fa-map-pin', label: 'Venue', val: 'RCC Lab, CSE' },
        ],
        student: 'Sujal Jain V - 9353058451\nAshay Amal - 9263432983',
        faculty: 'Dr. Srinivasa K\n98453 99083',
    },
    'ev6': {
        icon: '<i class="fas fa-pen-ruler"></i>',
        tag: 'WEB DESIGN',
        name: 'UI/UX PRINT',
        sub: 'Web Design Challenge',
        color: '#1a6aff',
        rules: [
            'Teams can use AI tools only as specified by the club. No other tools are allowed.',
            'A maximum of 10 prompts per AI tool is allowed.',
            'Teams must call volunteers every time a prompt is made.',
            'Participants must log into their own accounts and ensure AI tool history is saved.',
            'VS Code is mandatory for development.',
            'HTML, CSS, and JavaScript are compulsory; other frameworks may also be used.',
            'Teams must share their GitHub report at the end of the build.',
            '3 members per team.',
        ],
        info: [
            { icon: 'fa-users', label: 'Team Size', val: '3 members' },
            { icon: 'fa-robot', label: 'AI Prompts', val: 'Max 10 per tool' },
            { icon: 'fa-map-pin', label: 'Venue', val: 'Linux Laboratory, CSE' },
        ],
        student: 'Ujwal Pai - 97316 36663\nChaithra Aradhya - 81528 75878\nShalmala G Nadig - 90192 81825',
        faculty: 'Dr Anupama T A\n99003 98122',
    },
    'ev7': {
        icon: '<i class="fas fa-chart-line"></i>',
        tag: 'STARTUP PITCH',
        name: 'PITCHATHON',
        sub: 'Startup Pitch Competition',
        color: '#00f5ff',
        rules: [
            '3 members per team.',
            'Round 1: Present core idea via PPT.',
            'Round 2: Submit a persuasive video pitch (for shortlisted teams).',
            'Round 3: Solve a surprise challenge under constraints.',
            'Only PPT can be prepared in advance; all other work must be done during the event.',
            'All submissions must be original.',
            'Decisions are final; clarity, innovation, and feasibility are key.',
            'Adhere to deadlines and maintain professional teamwork throughout.',
        ],
        info: [
            { icon: 'fa-users', label: 'Team Size', val: '3 members' },
            { icon: 'fa-layer-group', label: 'Rounds', val: '3 rounds' },
            { icon: 'fa-map-pin', label: 'Venue', val: 'Kalpana Chawla Lab, CSE' },
        ],
        student: 'Raghavi M - 78991 23195\nAkshitha Katte - 96324 69914',
        faculty: 'Dr. Bhargavi K\n86182 03489',
    },
    'ev8': {
        icon: '<i class="fas fa-bolt"></i>',
        tag: 'HACKATHON',
        name: 'HYPERTHON',
        sub: 'AI Tools Hackathon',
        color: '#b400ff',
        rules: [
            'Topics will be given on the spot.',
            'No prework is allowed — development starts only after topic reveal.',
            'Participants will have 3 hours to build the prototype.',
            'Any and every AI tool is allowed during development.',
            'A working prototype is mandatory for evaluation.',
            'Individual participation only — no teams.',
            'Participants must be able to explain the methodology and tech stack used.',
        ],
        info: [
            { icon: 'fa-user', label: 'Type', val: 'Individual' },
            { icon: 'fa-clock', label: 'Duration', val: '3 hours' },
            { icon: 'fa-map-pin', label: 'Venue', val: 'Aryabhatta Computer Centre, CSE' },
        ],
        student: 'Ujwal Pai - 97316 36663\nArshan Ali Khan - 82960 15593',
        faculty: 'Dr. R M Savithramma\n84958 22888',
    },
};
