window.events = {
    'ev1': {
        icon: '<i class="fas fa-spell-check"></i>',
        tag: 'CYBER ETYMOLOGY',
        name: 'CYBER ETYMOLOGY',
        sub: 'Etymology: Derivation of Words from Originals',
        color: '#00f5ff',
        rules: [
            'It is a game of scrabble related to computer science.',
            '3 members per team.',
            'The game comprises of two rounds: Prelims & Finals.',
            'Each team will be given 5 characters, one at a time.',
            'Words framed with given characters should be technical terms related to electronics and computers.',
        ],
        info: [
            { icon: 'fa-users', label: 'Team Size', val: '3 members' },
            { icon: 'fa-layer-group', label: 'Rounds', val: '2 (Prelims & Finals)' },
            { icon: 'fa-map-pin', label: 'Venue', val: 'Research Lab, ISE' },
        ],
        studentCoordinators: [
            { name: 'Chirashree', contact: '+91 87621 93686' },
            { name: 'Nehil', contact: '+91 91312 03322' },
        ],
        facultyCoordinators: [
            { name: 'Dr. Nagaratna B Chittaragi', contact: '96062 25604' },
        ],
    },
    'ev2': {
        icon: '<i class="fas fa-brain"></i>',
        tag: 'TECHNICAL QUIZ',
        name: 'TECHNICAL QUIZ',
        sub: 'Facts, Personalities, Logos & Industry Trends',
        color: '#b400ff',
        rules: [
            '2 members per team.',
            'The QUIZ comprises of two rounds: Prelims & Finals.',
            'Quiz will be based on facts of computer technology, famous personalities, industry logos and recent trends in IT.',
        ],
        info: [
            { icon: 'fa-users', label: 'Team Size', val: '2 members' },
            { icon: 'fa-layer-group', label: 'Rounds', val: '2 (Prelims & Finals)' },
            { icon: 'fa-map-pin', label: 'Venue', val: 'Koutilya Lab, ISE' },
        ],
        studentCoordinators: [
            { name: 'Manoj', contact: '9008126740' },
            { name: 'Balaji', contact: '7090914581' },
            { name: 'Naveen', contact: '8618742198' },
        ],
        facultyCoordinators: [
            { name: 'Dr. Sharathkumar', contact: '95353 21023' },
        ],
    },
    'ev3': {
        icon: '<i class="fas fa-microphone"></i>',
        tag: 'TECH TALK',
        name: 'WITTY BYTE',
        sub: 'TECH TALK',
        color: '#39ff14',
        rules: [
            'It is an individual technical talk event.',
            'The WITTYBYTE comprises of four rounds.',
            'Tech talk will be based on talk related to a topic scenario or an image given on the spot.',
            'Usage of offensive words and violation of rules will result in immediate elimination.',
        ],
        info: [
            { icon: 'fa-user', label: 'Type', val: 'Individual' },
            { icon: 'fa-layer-group', label: 'Rounds', val: '4 rounds' },
            { icon: 'fa-map-pin', label: 'Venue', val: 'Project Lab, CSE' },
        ],
        studentCoordinators: [
            { name: 'Haradeep Reddy', contact: '7416719446' },
            { name: 'Sachin', contact: '9606426567' },
        ],
        facultyCoordinators: [
            { name: 'Dr. H D Kallinatha', contact: '99862 95070' },
        ],
    },
    'ev4': {
        icon: '<i class="fas fa-gamepad"></i>',
        tag: 'GAMING',
        name: 'LIFE EXTENSION',
        sub: 'GAMING CONTEST',
        color: '#ff0090',
        rules: [
            '<strong>Valorant</strong>',
            '5 members per team.',
            'Players must bring their own laptops.',
            'Internet facility will be provided.',
            '<br><strong>BGMI</strong>',
            '4 members per team.',
            'Game will be played in custom rules created by the host.',
            'Internet facility will be provided.',
        ],
        info: [
            { icon: 'fa-users', label: 'Valorant', val: '5 members' },
            { icon: 'fa-users', label: 'BGMI', val: '4 members' },
            { icon: 'fa-map-pin', label: 'Venue', val: 'Media Center/MBA Block' },
        ],
        studentCoordinators: [
            { name: 'Omsai Reddy', contact: '8861611227' },
            { name: 'Yashaswini P', contact: '+91 80886 88451' },
        ],
        facultyCoordinators: [
            { name: 'Dr. Keerthan Kumar', contact: '88846 74522' },
        ],
    },
    'ev5': {
        icon: '<i class="fas fa-terminal"></i>',
        tag: 'PROGRAMMING',
        name: 'BYTE SURGE',
        sub: 'Programming Contest',
        color: '#ff6b1a',
        rules: [
            'It is a Programming contest.',
            '2 members per team.',
            'The BYTE SURGE comprises of two rounds: Prelims & Finals.',
            'Language: C or C++',
        ],
        info: [
            { icon: 'fa-users', label: 'Team Size', val: '2 members' },
            { icon: 'fa-code', label: 'Language', val: 'C / C++' },
            { icon: 'fa-map-pin', label: 'Venue', val: 'RCC Lab, CSE' },
        ],
        studentCoordinators: [
            { name: 'Sujal Jain V', contact: '9353058451' },
            { name: 'Ashay Amal', contact: '9263432983' },
        ],
        facultyCoordinators: [
            { name: 'Dr. Srinivasa K', contact: '98453 99083' },
        ],
    },
    // UI/UX PRINT is not conducted this year. Keep this block for future editions.
    // 'ev6': {
    //     icon: '<i class="fas fa-pen-ruler"></i>',
    //     tag: 'WEB DESIGN',
    //     name: 'UI/UX PRINT',
    //     sub: 'Web Design Challenge',
    //     color: '#1a6aff',
    //     rules: [
    //         'Teams can use AI tools only as specified by the club. No other tools are allowed.',
    //         'A maximum of 10 prompts per AI tool is allowed.',
    //         'Teams must call volunteers every time a prompt is made.',
    //         'Participants must log into their own accounts and ensure AI tool history is saved.',
    //         'VS Code is mandatory for development.',
    //         'HTML, CSS, and JavaScript are compulsory; other frameworks may also be used.',
    //         'Teams must share their GitHub report at the end of the build.',
    //         '3 members per team.',
    //     ],
    //     info: [
    //         { icon: 'fa-users', label: 'Team Size', val: '3 members' },
    //         { icon: 'fa-robot', label: 'AI Prompts', val: 'Max 10 per tool' },
    //         { icon: 'fa-map-pin', label: 'Venue', val: 'Linux Laboratory, CSE' },
    //     ],
    //     studentCoordinators: [
    //         { name: 'Ujwal Pai', contact: '97316 36663' },
    //         { name: 'Chaithra Aradhya', contact: '81528 75878' },
    //         { name: 'Shalmala G Nadig', contact: '90192 81825' },
    //     ],
    //     facultyCoordinators: [
    //         { name: '', contact: '' },
    //     ],
    // },
    'ev7': {
        icon: '<i class="fas fa-chart-line"></i>',
        tag: 'STARTUP PITCH',
        name: 'PITCHATHON',
        sub: 'Startup Pitch Competition',
        color: '#00f5ff',
        rules: [
            '3 members per team.',
            'Round 1: Present core idea via PPT.',
            'Round 2: Submit a persuasive video pitch (for shortlisted teams).',
            'Round 3: Solve a surprise challenge under constraints.',
            'Only PPT can be prepared in advance; all other work must be done during the event.',
            'All submissions must be original.',
            'Decisions are final; clarity, innovation, and feasibility are key.',
            'Adhere to deadlines and maintain professional teamwork throughout.',
        ],
        info: [
            { icon: 'fa-users', label: 'Team Size', val: '3 members' },
            { icon: 'fa-layer-group', label: 'Rounds', val: '3 rounds' },
            { icon: 'fa-map-pin', label: 'Venue', val: 'Kalpana Chawla Lab, CSE' },
        ],
        studentCoordinators: [
            { name: 'Raghavi M', contact: '78991 23195' },
            { name: 'Akshitha Katte', contact: '96324 69914' },
        ],
        facultyCoordinators: [
            { name: 'Dr. Prasanna Kumar K R', contact: '' },
        ],
    },
    'ev8': {
        icon: '<i class="fas fa-bolt"></i>',
        tag: 'HACKATHON',
        name: 'HYPERTHON',
        sub: 'AI Tools Hackathon',
        color: '#b400ff',
        rules: [
            'Topics will be given on the spot.',
            'No prework is allowed — development starts only after topic reveal.',
            'Participants will have 3 hours to build the prototype.',
            'Any and every AI tool is allowed during development.',
            'A working prototype is mandatory for evaluation.',
            'Individual participation only — no teams.',
            'Participants must be able to explain the methodology and tech stack used.',
        ],
        info: [
            { icon: 'fa-user', label: 'Type', val: 'Individual' },
            { icon: 'fa-clock', label: 'Duration', val: '3 hours' },
            { icon: 'fa-map-pin', label: 'Venue', val: 'Aryabhatta Computer Centre, CSE' },
        ],
        studentCoordinators: [
            { name: 'Ujwal Pai', contact: '97316 36663' },
            { name: 'Arshan Ali Khan', contact: '82960 15593' },
        ],
        facultyCoordinators: [
            { name: 'Dr. R M Savithramma', contact: '84958 22888' },
        ],
    },
};
